// Generated by CoffeeScript 1.3.3
(function() {
  var Cutter;

  Cutter = (function() {

    function Cutter() {
      this.nx = 1;
      this.ny = 1;
      this.width = 1;
      this.height = 1;
    }

    Cutter.prototype.count = function() {
      return this.nx * this.ny;
    };

    Cutter.prototype.cut = function(image) {
      var h, pieces, shape, w, x, y, _i, _j, _ref, _ref1;
      this.width = image.width;
      this.height = image.height;
      w = Math.round(this.width / this.nx);
      h = Math.round(this.height / this.ny);
      pieces = new Array();
      for (y = _i = 0, _ref = this.ny; 0 <= _ref ? _i < _ref : _i > _ref; y = 0 <= _ref ? ++_i : --_i) {
        for (x = _j = 0, _ref1 = this.nx; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
          shape = new Shape();
          shape.graphics.beginBitmapFill(image);
          shape.graphics.drawRoundRect(x * w, y * h, w, h, w * 0.2);
          shape.boundary = [x * w, y * h, w, h];
          shape.cache.apply(shape, shape.boundary);
          pieces.push(shape);
        }
      }
      return pieces;
    };

    return Cutter;

  })();

  this.Cutter = Cutter;

}).call(this);
